  constructor(){
// this.faculty="vikas";
// console.log("hello constructor");
//     }

// let h=new hello();
// console.log(h.faculty);
// class student {
//     constructor(roll,name,year){
//         this.rollno=roll;
//         this.Name=name;
//         this.Year=year;
//         console.log(this.rollno);
//         console.log(this.Name);
//         console.log(this.Year);
//     }
// }
// let s1=new student();
// let s2=new student(101,"garima","2nd");
// let s3=new student(101,"garima","2nd");