function sum(...values){
//   let sum=0;
//   for(let i of values){
//     sum+=i;
//   }
//   console.log("sum",sum);
// };
// let ar=[1,2,3,4,5];
// sum(...ar);
// let a1=[10,20,30];
// let a2=[40,50];
// var a3=[...a1,...a2];
// console.log(a3)
// var a4=[60,...a1,70,...a2];
// console.log(a4)
// let name="vikas";
// let rollNumber=101;
// let data={
//   name,rollNumber
// }
// console.log(data.name)
// console.log(data.rollNumber)